apiVersion: batch/v1
kind: Job
metadata:
 name: pi-job
spec:
 template:
  spec: 
   containers:
   - name: pijob-container
     image: perl
     command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
   restartPolicy: Never
 backoffLimit: 4


# `kubectl get` to list and check the status of Jobs. ``` kubectl get jobs ```

